### ISSUE TITLE
connect not defined

### ISSUE THREAD

**Issue by njacot** [mkarliner/meteor-mqtt#5]
Hi

I am using meteor 1.5
I tried to run this code and the client side:
`var mqtt = require('meteor/mkarliner:mqtt');`
`var client  = mqtt.connect('mqtt://test.mosquitto.org');`

But in the Chrome console I get this error.
`Uncaught TypeError: mqtt.connect is not a function`

I installed the module like this:
`meteor add mkarliner:mqtt`

Do I need some pre-configuration code ?

Thanks

**Comment by mkarliner** [comment]
I'm not really maintaining this as Meteor now allows direct use of npm modules. 
Is mqtt.connect may be undefined, but is mqtt itself undefined or what?

**Comment by njacot** [comment]
I see,

I am new with meteor and mqtt, so I wanted to try your package.
I use the mqtt npm module now and it works fine on the server side but not on the client side.
that's also why I tried your package.

Thank you
